site_name: My Docs
site_url: https://github.com/
repo_url: https://github.com/
repo_name: MyRepository

nav:
  - Home:
      - README.md
  - Quickstart:
      - quickstart/install.md
  - Learn:
      - Main: learn/main.md
      - Concepts: learn/concepts.md
      - Examples: learn/examples.md
      - FAQ: learn/faq.md
  - Development:
      - Main: dev/main.md
      - VsCode: dev/vscode.md
      - Remote: dev/remote.md
      - Version Control: dev/version.md
      - Tests: dev/test.md
      - CI/CD: dev/cicd.md
      - CLI: dev/typer.md
      - Troubleshoot: dev/troubleshoot.md
  - References:
      - API: references/api.md
      - MkDocs: references/mkdocs.md
  - About:
      - about/LICENSE.md
      - about/author.md

theme:
  name: material
  palette:
    # Light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

  features:
    # Layout
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - search.suggest
    - navigation.footer
    - navigation.indexes

    # Code block
    - content.code.copy
    - content.code.annotate

  # Logo
  logo: assets/images/icon.png
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  # Common extensions
  - admonition
  - attr_list
  - md_in_html
  - tables

  # Pymarkdown
  - pymdownx.blocks.caption
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      pygments_lang_class: true

  # Emoji support
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - glightbox
  - privacy
  - search
  - termynal

  # Mkdocs auto code generation
  # https://stackoverflow.com/questions/74209148/automatically-generate-api-reference-for-all-subpackages-modules
  - mkdocstrings:
      handlers:
        python:
          options:
            show_submodules: true
