site_name: My Docs
site_url: https://github.com/
repo_url: https://github.com/
repo_name: MyRepository

nav:
  - Home:
      - README.md
  - Quickstart:
      - quickstart/install.md
  - Learn:
      - learn/basics.md
  - Development:
      - Note: dev/note.md
      - VsCode: dev/vscode.md
      - Remote: dev/remote.md
      - Version Control: dev/version.md
      - Tests: dev/test.md
      - CI/CD: dev/cicd.md
      - CLI: dev/typer.md
      - Troubleshoot: dev/troubleshoot.md
  - References:
      - references/mkdocs.md
  - About:
      - about/LICENSE.md
      - about/author.md

theme:
  name: material

  palette:
    # Light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

  features:
    # Layout
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - search.suggest

    # Code block
    - content.code.copy
    - content.code.annotate

  # Logo
  logo: assets/images/icon.png
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  # Table support
  - attr_list
  - tables

  # HTML support
  - md_in_html
  - pymdownx.blocks.caption

  # Fenced blocks
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite

  # Keys
  - pymdownx.keys

  # PyMarkdownX Configs
  - pymdownx.highlight:
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
