name: pytest

on:
  # Leave blank if you want to run on all branches.
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13", "3.14"]
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install uv and set python version
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Python ${{ matrix.python-version }} Install dependencies
        run: uv sync --all-extras

      - name: Python ${{ matrix.python-version }} Pytest
        run: >
          uv run pytest
          --cov=./
          --cov-report=xml
          --cov-report=html:pytest-results-${{ matrix.python-version }}

      - name: Python ${{ matrix.python-version }} Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results-${{ matrix.python-version }}
          path: pytest-results-${{ matrix.python-version }}

        if: ${{ always() }}
