name: zensical

on:
  push:
    branches:
      - master
      - main
      
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  zensical:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Configure GitHub Pages.  # can deploy from `docs` branch
        uses: actions/configure-pages@v5

      - name: Checkout repository.
        uses: actions/checkout@v5

      - name: Install Python.
        uses: actions/setup-python@v5
        with:
          python-version: 3.14

      - name: Install Zensical.
        run: pip install zensical

      - name: Zensical build.
        run: zensical build --clean 

      - name: Upload site pages.
        uses: actions/upload-pages-artifact@v4
        with:
          path: site  # the folder that zensical builds

      - name: Deploy the `site` pages.
        uses: actions/deploy-pages@v4
        id: deployment